### ISSUE TITLE
Doesn't compile with stable rust (1.85.0)

### ISSUE THREAD

**Issue by Madoshakalaka** [its-the-shrimp/yew-html-ext#12]
works on nightly but

```
error[E0599]: no function or associated item named `from_utf8` found for type `str` in the current scope
   --> /home/maa/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yew-html-ext-0.3.0/src/props/prop.rs:143:24
    |
143 |     let element = str::from_utf8(&buf)
    |                        ^^^^^^^^^ function or associated item not found in `str`
    |
help: you are looking for the module in `std`, not the primitive type
    |
143 |     let element = std::str::from_utf8(&buf)
    |                   +++++
```

**Comment by Madoshakalaka** [comment]
seems like they will add the method on the str type in 1.87

**Comment by its-the-shrimp** [comment]
Oops, I was using nightly as the default toolchain all this time, silly me
